---
driver:
  name: docker
  #  podman
platforms:
  - name: centos-7
    image: centos:centos7
    #quay.io/centos/centos:centos7
    # pre_build_image: true
    cgroupns_mode: host
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

provisioner:
  name: ansible
  log: true
  playbooks:
    converge: converge.yml
    # verify: verify.yml
